plugins {
	id 'fabric-loom' version '1.3.8'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
	maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
	inputs.property "version", project.version
	inputs.property "fabricLoader", project.loader_version
	inputs.property "fabricApi", project.fabric_version
	inputs.property "minecraftVersion", project.minecraft_version

	from(sourceSets.main.resources.srcDirs) {
		include "fabric.mod.json"
		expand "version": project.version,
			"fabricLoader": project.loader_version,
			"fabricApi": project.fabric_version,
			"minecraftVersion": project.minecraft_version
	}

	from(sourceSets.main.resources.srcDirs) {
		exclude "fabric.mod.json"
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename it, "LICENSE_${project.archivesBaseName}"
	}
}
